# Generated by Django 3.0.9 on 2020-08-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='regdate',
            field=models.CharField(default='08-07-2020', max_length=20),
            preserve_default=False,
        ),
    ]
